extract_featres:
	python3 feature_extraction.py

train_mlp_model:
	python3 mlp_model.py

train_cnn_model:
	python3 cnn_model.py	

test_mlp_model:
	python3 test_mlp_model.py	

test_cnn_model:
	python3 test_cnn_model.py		

